export const MODEL_REGISTRY: Record<string, { provider: string; mps: number; isLocal: boolean }> = {
  'Claude Opus 4.6': { provider: 'anthropic', mps: 98, isLocal: false },
  'GPT-5.4 Pro': { provider: 'openai', mps: 97, isLocal: false },
  'GPT-5.4': { provider: 'openai', mps: 95, isLocal: false },
  'Gemini 3.1 Ultra': { provider: 'google', mps: 93, isLocal: false },
  'Claude Sonnet 4.6': { provider: 'anthropic', mps: 92, isLocal: false },
  'GPT-5.3 Codex': { provider: 'openai', mps: 90, isLocal: false },
  'Claude Haiku 4.5': { provider: 'anthropic', mps: 85, isLocal: false },
  'GPT-5.4 Mini': { provider: 'openai', mps: 80, isLocal: false },
  'Gemini 3.1 Flash': { provider: 'google', mps: 78, isLocal: false },
  'Llama 3.3 70B': { provider: 'meta', mps: 75, isLocal: true },
  'DeepSeek V3': { provider: 'deepseek', mps: 70, isLocal: false },
  'Llama 3.1 70B': { provider: 'meta', mps: 65, isLocal: true },
  'Llama 3.3 8B': { provider: 'meta', mps: 55, isLocal: true },
  'Phi-4': { provider: 'microsoft', mps: 52, isLocal: true },
  'Mistral 7B': { provider: 'mistral', mps: 50, isLocal: true },
  'Gemma 3 9B': { provider: 'google', mps: 48, isLocal: true },
  'Llama 3.1 8B': { provider: 'meta', mps: 45, isLocal: true },
  'TinyLlama': { provider: 'meta', mps: 30, isLocal: true },
}
