-- ============================================================
-- Migration 00043 — Premium Post-Bout Feedback System
-- Forge · 2026-03-31
-- ============================================================
-- Creates the full data model for evidence-backed performance intelligence.
-- Separated into 7 tables covering: feedback reports, lane cards, failure modes,
-- improvement priorities, evidence refs, agent performance profiles, and events.
-- ============================================================

-- ── 1. submission_feedback_reports ───────────────────────────────────────────
-- One row per submission. The top-level diagnostic summary.
-- Generated by the feedback pipeline after judging completes.

CREATE TABLE IF NOT EXISTS public.submission_feedback_reports (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id           UUID NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
  entry_id                UUID REFERENCES public.challenge_entries(id) ON DELETE CASCADE,
  version                 INTEGER NOT NULL DEFAULT 1,
  status                  TEXT NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'generating', 'ready', 'failed', 'stale')),

  -- Top-level diagnosis
  overall_summary         TEXT,
  executive_diagnosis     TEXT,
  result_narrative        TEXT,       -- "What actually happened" in human prose

  -- Causal attribution
  primary_loss_driver     TEXT,       -- "validation_omission" etc — from taxonomy
  secondary_loss_driver   TEXT,
  decisive_moment         TEXT,       -- The single pivot point that swung the result

  -- Character signals
  dominant_strength       TEXT,       -- The agent's clearest positive trait this bout
  dominant_weakness       TEXT,       -- The agent's clearest negative trait this bout

  -- Coaching
  highest_leverage_fix    TEXT,       -- Fix first
  next_best_fix           TEXT,       -- Fix next

  -- Confidence metadata
  confidence_overall      TEXT DEFAULT 'medium'
                          CHECK (confidence_overall IN ('high', 'medium', 'low')),
  evidence_density_score  NUMERIC(4,1),     -- 0–10
  ambiguity_level         TEXT DEFAULT 'low'
                          CHECK (ambiguity_level IN ('low', 'medium', 'high')),

  -- Audit trail
  generated_by_model      TEXT,
  generation_ms           INTEGER,
  pipeline_version        TEXT DEFAULT 'v1',
  error_message           TEXT,

  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sfr_submission_id ON public.submission_feedback_reports(submission_id);
CREATE INDEX IF NOT EXISTS idx_sfr_entry_id ON public.submission_feedback_reports(entry_id);
CREATE INDEX IF NOT EXISTS idx_sfr_status ON public.submission_feedback_reports(status);

-- ── 2. submission_lane_feedback ───────────────────────────────────────────────
-- Per-lane scorecard. One row per lane per submission.
-- Each card is a full diagnostic: score, percentile, behaviors, drivers, coaching.

CREATE TABLE IF NOT EXISTS public.submission_lane_feedback (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id           UUID NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
  entry_id                UUID REFERENCES public.challenge_entries(id) ON DELETE CASCADE,
  feedback_report_id      UUID REFERENCES public.submission_feedback_reports(id) ON DELETE CASCADE,
  lane                    TEXT NOT NULL CHECK (lane IN ('objective', 'process', 'strategy', 'integrity', 'audit')),
  score                   NUMERIC(5,1),
  percentile              NUMERIC(5,1),     -- null until enough submissions exist
  confidence              TEXT DEFAULT 'medium'
                          CHECK (confidence IN ('high', 'medium', 'low')),

  -- Behavioral observations
  strongest_behavior      TEXT,     -- Most concrete positive thing observed
  weakest_behavior        TEXT,     -- Most concrete negative thing observed

  -- Causal analysis
  primary_driver          TEXT,     -- Root cause of the lane result (specific)
  secondary_driver        TEXT,

  -- What-happened blocks (display-ready prose)
  what_went_right         TEXT,
  what_went_wrong         TEXT,
  what_this_means         TEXT,     -- Interpretation / so-what
  improvement_recommendation TEXT,  -- Specific, actionable coaching line

  -- Evidence
  evidence_refs_json      JSONB DEFAULT '[]',   -- Array of ref IDs or inline refs

  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (submission_id, lane)
);

CREATE INDEX IF NOT EXISTS idx_slf_submission_id ON public.submission_lane_feedback(submission_id);
CREATE INDEX IF NOT EXISTS idx_slf_entry_id ON public.submission_lane_feedback(entry_id);
CREATE INDEX IF NOT EXISTS idx_slf_feedback_report_id ON public.submission_lane_feedback(feedback_report_id);

-- ── 3. submission_failure_modes ───────────────────────────────────────────────
-- Controlled failure taxonomy classification per submission.
-- One submission can have multiple failure modes; primary_flag distinguishes the dominant.
--
-- Taxonomy v1 (15 codes):
--   hidden_constraint_miss      — agent ignored a non-obvious constraint
--   validation_omission         — output not verified before finalizing
--   premature_convergence       — locked first viable path without exploration
--   brittle_workaround          — fix breaks under slight variation
--   hallucinated_completion     — claimed done when not actually complete
--   unsupported_certainty       — expressed confidence without evidence
--   misleading_implication      — output implies correctness it doesn't have
--   poor_recovery               — didn't recover well from early errors
--   spec_drift                  — solution drifted from original requirements
--   shallow_decomposition       — skipped depth on hard sub-problems
--   tool_misuse                 — misused available tools / wrong tool for job
--   overoptimized_visible_req   — nailed visible requirements, ignored hidden ones
--   sacrificed_reliability      — traded correctness for speed
--   format_noncompliance        — output violated required format
--   timeout_pacing_collapse     — ran out of time / wasted budget on wrong things

CREATE TABLE IF NOT EXISTS public.submission_failure_modes (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id     UUID NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
  entry_id          UUID REFERENCES public.challenge_entries(id) ON DELETE CASCADE,
  feedback_report_id UUID REFERENCES public.submission_feedback_reports(id) ON DELETE CASCADE,

  failure_mode_code TEXT NOT NULL CHECK (failure_mode_code IN (
    'hidden_constraint_miss',
    'validation_omission',
    'premature_convergence',
    'brittle_workaround',
    'hallucinated_completion',
    'unsupported_certainty',
    'misleading_implication',
    'poor_recovery',
    'spec_drift',
    'shallow_decomposition',
    'tool_misuse',
    'overoptimized_visible_req',
    'sacrificed_reliability',
    'format_noncompliance',
    'timeout_pacing_collapse',
    'none_detected'
  )),
  severity          TEXT NOT NULL DEFAULT 'medium'
                    CHECK (severity IN ('critical', 'high', 'medium', 'low')),
  confidence        TEXT NOT NULL DEFAULT 'medium'
                    CHECK (confidence IN ('high', 'medium', 'low')),
  primary_flag      BOOLEAN NOT NULL DEFAULT false,   -- true = dominant failure mode
  explanation       TEXT,       -- Human-readable, specific to this submission
  evidence_refs_json JSONB DEFAULT '[]',

  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sfm_submission_id ON public.submission_failure_modes(submission_id);
CREATE INDEX IF NOT EXISTS idx_sfm_entry_id ON public.submission_failure_modes(entry_id);
CREATE INDEX IF NOT EXISTS idx_sfm_failure_mode_code ON public.submission_failure_modes(failure_mode_code);
CREATE INDEX IF NOT EXISTS idx_sfm_primary_flag ON public.submission_failure_modes(primary_flag) WHERE primary_flag = true;

-- ── 4. submission_improvement_priorities ──────────────────────────────────────
-- Ranked coaching recommendations. Fix first → fix next → stretch.
-- Each includes specificity, expected impact, and difficulty signal.

CREATE TABLE IF NOT EXISTS public.submission_improvement_priorities (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id            UUID NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
  entry_id                 UUID REFERENCES public.challenge_entries(id) ON DELETE CASCADE,
  feedback_report_id       UUID REFERENCES public.submission_feedback_reports(id) ON DELETE CASCADE,

  priority_rank            INTEGER NOT NULL CHECK (priority_rank BETWEEN 1 AND 10),
  priority_tier            TEXT NOT NULL DEFAULT 'fix_first'
                           CHECK (priority_tier IN ('fix_first', 'fix_next', 'stretch')),
  title                    TEXT NOT NULL,         -- Short label (e.g. "Add constraint verification")
  recommendation           TEXT NOT NULL,         -- Specific coaching text
  rationale                TEXT,                  -- Why this matters for this submission
  expected_impact          TEXT NOT NULL DEFAULT 'medium'
                           CHECK (expected_impact IN ('high', 'medium', 'low')),
  implementation_difficulty TEXT NOT NULL DEFAULT 'medium'
                           CHECK (implementation_difficulty IN ('low', 'medium', 'high')),
  lane_target              TEXT CHECK (lane_target IN ('objective', 'process', 'strategy', 'integrity', 'all')),

  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (submission_id, priority_rank)
);

CREATE INDEX IF NOT EXISTS idx_sip_submission_id ON public.submission_improvement_priorities(submission_id);
CREATE INDEX IF NOT EXISTS idx_sip_entry_id ON public.submission_improvement_priorities(entry_id);

-- ── 5. submission_evidence_refs ───────────────────────────────────────────────
-- Every substantive claim in the feedback should link to inspectable evidence.
-- Types: transcript_excerpt, tool_trace, output_diff, rule_check, judge_note,
--        artifact, integrity_mismatch, timing_event

CREATE TABLE IF NOT EXISTS public.submission_evidence_refs (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id   UUID NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
  entry_id        UUID REFERENCES public.challenge_entries(id) ON DELETE CASCADE,
  feedback_report_id UUID REFERENCES public.submission_feedback_reports(id) ON DELETE CASCADE,

  ref_type        TEXT NOT NULL CHECK (ref_type IN (
    'transcript_excerpt',
    'tool_trace',
    'output_diff',
    'rule_check',
    'judge_note',
    'artifact',
    'integrity_mismatch',
    'timing_event',
    'lane_score',
    'metric_signal'
  )),
  ref_key         TEXT,           -- e.g. "step_34", "tool_call_12", "judge_output_uuid"
  label           TEXT NOT NULL,  -- Display label
  excerpt         TEXT,           -- The actual quoted text / signal
  relevance       TEXT,           -- Why this evidence matters
  metadata_json   JSONB DEFAULT '{}',

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ser_submission_id ON public.submission_evidence_refs(submission_id);
CREATE INDEX IF NOT EXISTS idx_ser_entry_id ON public.submission_evidence_refs(entry_id);
CREATE INDEX IF NOT EXISTS idx_ser_ref_type ON public.submission_evidence_refs(ref_type);

-- ── 6. agent_performance_profiles ────────────────────────────────────────────
-- Longitudinal agent-level performance memory.
-- Updated after every completed bout. One row per agent.

CREATE TABLE IF NOT EXISTS public.agent_performance_profiles (
  id                              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id                        UUID NOT NULL UNIQUE REFERENCES public.agents(id) ON DELETE CASCADE,

  -- Rolling counters
  total_bouts                     INTEGER NOT NULL DEFAULT 0,
  total_production_bouts          INTEGER NOT NULL DEFAULT 0,

  -- Rolling scores (simple exponential average, α=0.3)
  rolling_overall_score           NUMERIC(5,1),
  rolling_objective_score         NUMERIC(5,1),
  rolling_process_score           NUMERIC(5,1),
  rolling_strategy_score          NUMERIC(5,1),
  rolling_integrity_score         NUMERIC(5,1),

  -- Score volatility (std-dev proxy — rolling range of last 5 scores)
  score_volatility                NUMERIC(5,1),

  -- Pattern memory (JSONB arrays — top N items by frequency)
  recurring_strengths_json        JSONB DEFAULT '[]',   -- [{code, label, count, last_seen}]
  recurring_weaknesses_json       JSONB DEFAULT '[]',
  recurring_failure_modes_json    JSONB DEFAULT '[]',   -- [{failure_mode_code, count, last_seen}]

  -- Lane trend data [{lane, scores: [last 10], trend_direction, last_updated}]
  lane_trends_json                JSONB DEFAULT '{}',

  -- Volatility breakdown by lane
  volatility_metrics_json         JSONB DEFAULT '{}',

  -- Improvement signals [{area, direction: 'improving'|'declining'|'stable', confidence}]
  improvement_trends_json         JSONB DEFAULT '[]',

  -- Per challenge-type performance [{type, avg_score, count}]
  challenge_type_performance_json JSONB DEFAULT '{}',

  -- Regression warnings [{lane, warning, detected_at}]
  regression_warnings_json        JSONB DEFAULT '[]',

  -- Last 5 bout summaries for context [{submission_id, composite_score, primary_failure, date}]
  recent_bouts_json               JSONB DEFAULT '[]',

  last_updated_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_app_agent_id ON public.agent_performance_profiles(agent_id);

-- ── 7. agent_performance_events ───────────────────────────────────────────────
-- Immutable event log for the longitudinal profile.
-- event_types: bout_completed, regression_detected, improvement_detected,
--              failure_mode_recurring, strength_emerging, profile_updated

CREATE TABLE IF NOT EXISTS public.agent_performance_events (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id        UUID NOT NULL REFERENCES public.agents(id) ON DELETE CASCADE,
  submission_id   UUID REFERENCES public.submissions(id) ON DELETE SET NULL,
  entry_id        UUID REFERENCES public.challenge_entries(id) ON DELETE SET NULL,

  event_type      TEXT NOT NULL CHECK (event_type IN (
    'bout_completed',
    'regression_detected',
    'improvement_detected',
    'failure_mode_recurring',
    'strength_emerging',
    'profile_created',
    'profile_updated',
    'warning_issued'
  )),
  payload_json    JSONB DEFAULT '{}',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ape_agent_id ON public.agent_performance_events(agent_id);
CREATE INDEX IF NOT EXISTS idx_ape_event_type ON public.agent_performance_events(event_type);
CREATE INDEX IF NOT EXISTS idx_ape_created_at ON public.agent_performance_events(created_at DESC);

-- ── RLS ───────────────────────────────────────────────────────────────────────
-- Feedback reports, lane feedback, failure modes, priorities, evidence:
--   Owner (via entry) can read their own. Admin reads all.
-- Agent performance profiles / events:
--   Owner can read their own agent's profile. Admin reads all.

ALTER TABLE public.submission_feedback_reports     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submission_lane_feedback        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submission_failure_modes        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submission_improvement_priorities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submission_evidence_refs        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_performance_profiles      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_performance_events        ENABLE ROW LEVEL SECURITY;

-- submission_feedback_reports
CREATE POLICY "sfr_owner_read" ON public.submission_feedback_reports FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.submissions s
      WHERE s.id = submission_id AND s.user_id = auth.uid()
    )
  );
CREATE POLICY "sfr_admin_read" ON public.submission_feedback_reports FOR SELECT
  USING (public.is_admin());

-- submission_lane_feedback
CREATE POLICY "slf_owner_read" ON public.submission_lane_feedback FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.submissions s
      WHERE s.id = submission_id AND s.user_id = auth.uid()
    )
  );
CREATE POLICY "slf_admin_read" ON public.submission_lane_feedback FOR SELECT
  USING (public.is_admin());

-- submission_failure_modes
CREATE POLICY "sfm_owner_read" ON public.submission_failure_modes FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.submissions s
      WHERE s.id = submission_id AND s.user_id = auth.uid()
    )
  );
CREATE POLICY "sfm_admin_read" ON public.submission_failure_modes FOR SELECT
  USING (public.is_admin());

-- submission_improvement_priorities
CREATE POLICY "sip_owner_read" ON public.submission_improvement_priorities FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.submissions s
      WHERE s.id = submission_id AND s.user_id = auth.uid()
    )
  );
CREATE POLICY "sip_admin_read" ON public.submission_improvement_priorities FOR SELECT
  USING (public.is_admin());

-- submission_evidence_refs
CREATE POLICY "ser_owner_read" ON public.submission_evidence_refs FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.submissions s
      WHERE s.id = submission_id AND s.user_id = auth.uid()
    )
  );
CREATE POLICY "ser_admin_read" ON public.submission_evidence_refs FOR SELECT
  USING (public.is_admin());

-- agent_performance_profiles
CREATE POLICY "app_owner_read" ON public.agent_performance_profiles FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.agents a
      WHERE a.id = agent_id AND a.user_id = auth.uid()
    )
  );
CREATE POLICY "app_admin_read" ON public.agent_performance_profiles FOR SELECT
  USING (public.is_admin());

-- agent_performance_events
CREATE POLICY "ape_owner_read" ON public.agent_performance_events FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.agents a
      WHERE a.id = agent_id AND a.user_id = auth.uid()
    )
  );
CREATE POLICY "ape_admin_read" ON public.agent_performance_events FOR SELECT
  USING (public.is_admin());

-- ── updated_at trigger ────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sfr_updated_at ON public.submission_feedback_reports;
CREATE TRIGGER sfr_updated_at
  BEFORE UPDATE ON public.submission_feedback_reports
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS app_updated_at ON public.agent_performance_profiles;
CREATE TRIGGER app_updated_at
  BEFORE UPDATE ON public.agent_performance_profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- End of migration 00043
-- Apply in Supabase SQL editor.
-- After applying:
--   SELECT table_name FROM information_schema.tables
--   WHERE table_schema = 'public'
--   AND table_name LIKE '%feedback%' OR table_name LIKE '%agent_performance%';
-- Should return: submission_feedback_reports, submission_lane_feedback,
--   submission_failure_modes, submission_improvement_priorities,
--   submission_evidence_refs, agent_performance_profiles, agent_performance_events
-- ============================================================
